<a href="https://colab.research.google.com/github/WdL01/Inventory-and-Sales-System/blob/main/web_scraping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from bs4 import BeautifulSoup
import requests

In [ ]:
url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_Philippines'

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
page = requests.get(url, headers=headers)
soup = BeautifulSoup(page.text, 'html')

In [ ]:
print(soup)

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-feature-navigation-update-disabled vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>List of largest companies in the Philippines - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-feature-navigation-update-disabled vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"26d5cac9-a931-42a0-9d49-ba1e3ef7d716","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_largest_companies_in_the_Philippines","wgTitle":"List of largest companies in the Philippines","wgCurRevisionId":1323855775,"wgRevisionId":1323855775,"wgArticleId":77677025,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Lists of largest private companies by country","Lists of companies of the Philippines"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_largest_companies_in_the_Philippines","wgRelevantArticleId":77677025,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}},"namespaces":[0,4]},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerMobileBeta":false,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":8000,"wgParsoidHtmlVersion":"2.8.0","parsermigration-parsoid":true,"wgPageAssessments":{"Lists":{"class":"List","importance":"Unknown"},"Project-independent assessment":{"class":"List","importance":""}},"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":true,"wgWikibaseItemId":"Q130235855","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgPersonalDashboardMenuVisible":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.parsoid.styles":"ready","ext.cite.styles":"ready","mediawiki.skinning.content.parsoid":"ready","ext.wikimediamessages.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","site","mediawiki.page.ready","jquery.tablesorter","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.parsoid.styles%7Cext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.tablesorter.styles%7Cmediawiki.skinning.content.parsoid%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.47.0-wmf.16" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="width=1120" name="viewport"/>
<meta content="List of largest companies in the Philippines - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="/w/index.php?title=List_of_largest_companies_in_the_Philippines&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_Philippines" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch"/>
<link href="auth.wikimedia.org" rel="dns-prefetch"/>
</head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_largest_companies_in_the_Philippines rootpage-List_of_largest_companies_in_the_Philippines skin-vector-2022 action-view">
<div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header no-font-mode-scale">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button aria-label="Move Main menu to sidebar" class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button aria-label="Hide Main menu" class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li class="mw-list-item" id="n-specialpages"><a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]"><span>Special pages</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search cdx-button__icon"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item vector-menu-item--collapsible" id="pt-sitesupport-2"><a class="" data-mw-donate-attempt="top_link" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-createaccount-2"><a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+in+the+Philippines" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-login-2"><a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+companies+in+the+Philippines" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out vector-user-links-dropdown--collapsible" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-userAvatar mw-ui-icon-wikimedia-userAvatar cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item vector-menu-item--collapsible" id="pt-sitesupport"><a class="" data-mw-donate-attempt="top_link" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span class="vector-icon mw-ui-icon-heart mw-ui-icon-wikimedia-heart cdx-button__icon"></span>
<span>Donate</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-createaccount"><a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+in+the+Philippines" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAvatar mw-ui-icon-wikimedia-userAvatar cdx-button__icon"></span>
<span>Create account</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-login"><a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+companies+in+the+Philippines" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn cdx-button__icon"></span>
<span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
</div>
</nav>
</div>
</header>
</div>
<div class="mw-page-container">
<div class="mw-page-container-inner">
<div class="vector-sitenotice-container">
<div id="siteNotice"><!-- CentralNotice --></div>

In [ ]:
len(soup.find_all('table'))

2

In [ ]:
soup.find_all('table')[0]

<table class="wikitable sortable" id="mwGg">
<tbody id="mwGw"><tr id="mwHA"><th id="mwHQ">Rank</th>
<th id="mwHg">Name</th>
<th id="mwHw">Industry</th>
<th id="mwIA">Revenue<br id="mwIQ"/><small id="mwIg">(USD millions)</small></th>
<th id="mwIw">Profits<br id="mwJA"/><small id="mwJQ">(USD millions)</small></th>
<th id="mwJg">Employees</th>
<th id="mwJw">Headquarters</th></tr>
<tr id="mwKA">
<td id="mwKQ">1</td>
<td id="mwKg"><a href="https://en.wikipedia.org/wiki/San_Miguel_Corporation" id="mwKw" rel="mw:WikiLink" title="San Miguel Corporation">San Miguel Corporation</a></td>
<td id="mwLA">Conglomerate</td>
<td id="mwLQ" style="text-align:center;">26,024</td>
<td id="mwLg" style="text-align:center;">4</td>
<td id="mwLw" style="text-align:center;">53,184</td>
<td id="mwMA"><a href="https://en.wikipedia.org/wiki/Mandaluyong" id="mwMQ" rel="mw:WikiLink" title="Mandaluyong">Mandaluyong</a></td></tr>
<tr id="mwMg">
<td id="mwMw">2</td>
<td id="mwNA"><a href="https://en.wikipedia.org/wiki/SM_Investments" id="mwNQ" rel="mw:WikiLink" title="SM Investments">SM Investments</a></td>
<td id="mwNg">Conglomerate</td>
<td id="mwNw" style="text-align:center;">10,277</td>
<td id="mwOA" style="text-align:center;">1,385</td>
<td id="mwOQ" style="text-align:center;">72,770</td>
<td id="mwOg"><a href="https://en.wikipedia.org/wiki/Pasay" id="mwOw" rel="mw:WikiLink" title="Pasay">Pasay</a></td></tr>
<tr id="mwPA">
<td id="mwPQ">3</td>
<td id="mwPg"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Manila_Electric" id="mwPw" rel="mw:WikiLink" title="Manila Electric">Manila Electric</a></td>
<td id="mwQA">Utilities</td>
<td id="mwQQ" style="text-align:center;">7,980</td>
<td id="mwQg" style="text-align:center;">684</td>
<td id="mwQw" style="text-align:center;">14,494</td>
<td id="mwRA"><a href="https://en.wikipedia.org/wiki/Pasig" id="mwRQ" rel="mw:WikiLink" title="Pasig">Pasig</a></td></tr>
<tr id="mwRg">
<td id="mwRw">4</td>
<td id="mwSA"><a href="https://en.wikipedia.org/wiki/JG_Summit_Holdings" id="mwSQ" rel="mw:WikiLink" title="JG Summit Holdings">JG Summit Holdings</a></td>
<td id="mwSg">Conglomerate</td>
<td id="mwSw" style="text-align:center;">5,932</td>
<td id="mwTA" style="text-align:center;">361</td>
<td id="mwTQ" style="text-align:center;">25,979</td>
<td id="mwTg">Pasig</td></tr>
<tr id="mwTw">
<td id="mwUA">5</td>
<td id="mwUQ"><a href="https://en.wikipedia.org/wiki/Banco_de_Oro" id="mwUg" rel="mw:WikiLink" title="Banco de Oro">Banco de Oro</a></td>
<td id="mwUw">Banking</td>
<td id="mwVA" style="text-align:center;">5,832</td>
<td id="mwVQ" style="text-align:center;">1,321</td>
<td id="mwVg" style="text-align:center;">41,647</td>
<td id="mwVw">Mandaluyong</td></tr>
<tr id="mwWA">
<td id="mwWQ">6</td>
<td id="mwWg"><a href="https://en.wikipedia.org/wiki/Aboitiz_Equity_Ventures" id="mwWw" rel="mw:WikiLink" title="Aboitiz Equity Ventures">Aboitiz Equity Ventures</a></td>
<td id="mwXA">Conglomerate</td>
<td id="mwXQ" style="text-align:center;">5,588</td>
<td id="mwXg" style="text-align:center;">424</td>
<td id="mwXw" style="text-align:center;">13,802</td>
<td id="mwYA"><a href="https://en.wikipedia.org/wiki/Taguig" id="mwYQ" rel="mw:WikiLink" title="Taguig">Taguig</a></td></tr>
<tr id="mwYg">
<td id="mwYw">7</td>
<td id="mwZA"><a href="https://en.wikipedia.org/wiki/Ayala_Corporation" id="mwZQ" rel="mw:WikiLink" title="Ayala Corporation">Ayala Corporation</a></td>
<td id="mwZg">Conglomerate</td>
<td id="mwZw" style="text-align:center;">5,215</td>
<td id="mwaA" style="text-align:center;">685</td>
<td id="mwaQ" style="text-align:center;">33,889</td>
<td id="mwag"><a href="https://en.wikipedia.org/wiki/Makati" id="mwaw" rel="mw:WikiLink" title="Makati">Makati</a></td></tr>
<tr id="mwbA">
<td id="mwbQ">8</td>
<td id="mwbg"><a href="https://en.wikipedia.org/wiki/GT_Capital" id="mwbw" rel="mw:WikiLink" title="GT Capital">GT Capital</a></td>
<td id="mwcA">Conglomerate</td>
<td id="mwcQ" style="text-align:center;">5,105</td>
<td id="mwcg" style="text-align:center;">517</td>
<td id="mwcw" style="text-align:center;">39,000</td>
<td id="mwdA">Makati</td></tr>
<tr id="mwdQ">
<td id="mwdg">9</td>
<td id="mwdw"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Jollibee_Foods_Corporation" id="mweA" rel="mw:WikiLink" title="Jollibee Foods Corporation">Jollibee Foods Corporation</a></td>
<td id="mweQ">Restaurants</td>
<td id="mweg" style="text-align:center;">4,391</td>
<td id="mwew" style="text-align:center;">158</td>
<td id="mwfA" style="text-align:center;">26,263</td>
<td id="mwfQ">Pasig</td></tr>
<tr id="mwfg">
<td id="mwfw">10</td>
<td id="mwgA"><a href="https://en.wikipedia.org/wiki/Cosco_Capital" id="mwgQ" rel="mw:WikiLink" title="Cosco Capital">Cosco Capital</a></td>
<td id="mwgg">Conglomerate</td>
<td id="mwgw" style="text-align:center;">3,858</td>
<td id="mwhA" style="text-align:center;">133</td>
<td id="mwhQ" style="text-align:center;">12,982</td>
<td id="mwhg"><a href="https://en.wikipedia.org/wiki/Manila" id="mwhw" rel="mw:WikiLink" title="Manila">Manila</a></td></tr>
<tr id="mwiA">
<td id="mwiQ">11</td>
<td id="mwig"><a href="https://en.wikipedia.org/wiki/PLDT" id="mwiw" rel="mw:WikiLink" title="PLDT">PLDT</a></td>
<td id="mwjA">Telecommunications</td>
<td id="mwjQ" style="text-align:center;">3,795</td>
<td id="mwjg" style="text-align:center;">479</td>
<td id="mwjw" style="text-align:center;">10,004</td>
<td id="mwkA">Makati</td></tr>
<tr id="mwkQ">
<td id="mwkg">12</td>
<td id="mwkw"><a href="https://en.wikipedia.org/wiki/Alliance_Global" id="mwlA" rel="mw:WikiLink" title="Alliance Global">Alliance Global</a></td>
<td id="mwlQ">Conglomerate</td>
<td id="mwlg" style="text-align:center;">3,683</td>
<td id="mwlw" style="text-align:center;">352</td>
<td id="mwmA" style="text-align:center;">56,915</td>
<td id="mwmQ">Manila</td></tr>
<tr id="mwmg">
<td id="mwmw">13</td>
<td id="mwnA"><a href="https://en.wikipedia.org/wiki/Robinsons_Retail" id="mwnQ" rel="mw:WikiLink" title="Robinsons Retail">Robinsons Retail</a></td>
<td id="mwng">Retail</td>
<td id="mwnw" style="text-align:center;">3,456</td>
<td id="mwoA" style="text-align:center;">74</td>
<td id="mwoQ" style="text-align:center;">23,172</td>
<td id="mwog">Pasig</td></tr>
<tr id="mwow">
<td id="mwpA">14</td>
<td id="mwpQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Metropolitan_Bank_&amp;_Trust_Company" id="mwpg" rel="mw:WikiLink" title="Metropolitan Bank &amp; Trust Company">Metropolitan Bank &amp; Trust</a></td>
<td id="mwpw">Banking</td>
<td id="mwqA" style="text-align:center;">3,292</td>
<td id="mwqQ" style="text-align:center;">760</td>
<td id="mwqg" style="text-align:center;">18,810</td>
<td id="mwqw">Makati</td></tr>
<tr id="mwrA">
<td id="mwrQ">15</td>
<td id="mwrg"><a href="https://en.wikipedia.org/wiki/Globe_Telecom" id="mwrw" rel="mw:WikiLink" title="Globe Telecom">Globe Telecom</a></td>
<td id="mwsA">Telecommunications</td>
<td id="mwsQ" style="text-align:center;">3,241</td>
<td id="mwsg" style="text-align:center;">441</td>
<td id="mwsw" style="text-align:center;">7,542</td>
<td id="mwtA">Taguig</td></tr>
<tr id="mwtQ">
<td id="mwtg">16</td>
<td id="mwtw"><a href="https://en.wikipedia.org/wiki/Bank_of_the_Philippine_Islands" id="mwuA" rel="mw:WikiLink" title="Bank of the Philippine Islands">Bank of the Philippine Islands</a></td>
<td id="mwuQ">Banking</td>
<td id="mwug" style="text-align:center;">3,239</td>
<td id="mwuw" style="text-align:center;">930</td>
<td id="mwvA" style="text-align:center;">19,522</td>
<td id="mwvQ">Makati</td></tr>
<tr id="mwvg">
<td id="mwvw">17</td>
<td id="mwwA"><a href="https://en.wikipedia.org/wiki/Philippine_Airlines" id="mwwQ" rel="mw:WikiLink" title="Philippine Airlines">PAL Holdings</a></td>
<td id="mwwg">Airline</td>
<td id="mwww" style="text-align:center;">3,222</td>
<td id="mwxA" style="text-align:center;">302</td>
<td id="mwxQ" style="text-align:center;">5,109</td>
<td id="mwxg">Pasay</td></tr>
<tr id="mwxw">
<td id="mwyA">18</td>
<td id="mwyQ"><a href="https://en.wikipedia.org/wiki/Lopez_Holdings_Corporation" id="mwyg" rel="mw:WikiLink" title="Lopez Holdings Corporation">Lopez Holdings Corporation</a></td>
<td id="mwyw">Conglomerate</td>
<td id="mwzA" style="text-align:center;">2,967</td>
<td id="mwzQ" style="text-align:center;">51</td>
<td id="mwzg" style="text-align:center;">11</td>
<td id="mwzw">Mandaluyong</td></tr>
<tr id="mw0A">
<td id="mw0Q">19</td>
<td id="mw0g"><a href="https://en.wikipedia.org/wiki/International_Container_Terminal_Services" id="mw0w" rel="mw:WikiLink" title="International Container Terminal Services">International Container Terminal Services</a></td>
<td id="mw1A">Port management</td>
<td id="mw1Q" style="text-align:center;">2,480</td>
<td id="mw1g" style="text-align:center;">512</td>
<td id="mw1w" style="text-align:center;">10,297</td>
<td id="mw2A">Manila</td></tr>
<tr id="mw2Q">
<td id="mw2g">20</td>
<td id="mw2w"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/DMCI_Holdings" id="mw3A" rel="mw:WikiLink" title="DMCI Holdings">DMCI Holdings</a></td>
<td id="mw3Q">Real estate</td>
<td id="mw3g" style="text-align:center;">2,210</td>
<td id="mw3w" style="text-align:center;">445</td>
<td id="mw4A" style="text-align:center;">17,620</td>
<td id="mw4Q">Makati</td></tr>
<tr id="mw4g">
<td id="mw4w">21</td>
<td id="mw5A"><a href="https://en.wikipedia.org/wiki/LT_Group" id="mw5Q" rel="mw:WikiLink" title="LT Group">LT Group</a></td>
<td id="mw5g">Conglomerate</td>
<td id="mw5w" style="text-align:center;">2,074</td>
<td id="mw6A" style="text-align:center;">457</td>
<td id="mw6Q" style="text-align:center;">14,296</td>
<td id="mw6g">Taguig</td></tr>
<tr id="mw6w">
<td id="mw7A">22</td>
<td id="mw7Q"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Unionbank_(Philippines)" id="mw7g" rel="mw:WikiLink" title="Unionbank (Philippines)">Unionbank</a></td>
<td id="mw7w">Banking</td>
<td id="mw8A" style="text-align:center;">1,751</td>
<td id="mw8Q" style="text-align:center;">163</td>
<td id="mw8g" style="text-align:center;">8,519</td>
<td id="mw8w">Pasig</td></tr>
<tr id="mw9A">
<td id="mw9Q">23</td>
<td id="mw9g"><a href="https://en.wikipedia.org/wiki/Filinvest" id="mw9w" rel="mw:WikiLink" title="Filinvest">Filinvest</a></td>
<td id="mw-A">Real estate</td>
<td id="mw-Q" style="text-align:center;">1,670</td>
<td id="mw-g" style="text-align:center;">161</td>
<td id="mw-w" style="text-align:center;">12,979</td>
<td id="mw_A">Taguig</td></tr>
<tr id="mw_Q">
<td id="mw_g">24</td>
<td id="mw_w"><a href="https://en.wikipedia.org/wiki/Rizal_Commercial_Banking_Corporation" id="mwAQA" rel="mw:WikiLink" title="Rizal Commercial Banking Corporation">Rizal Commercial Banking</a></td>
<td id="mwAQE">Banking</td>
<td id="mwAQI" style="text-align:center;">1,487</td>
<td id="mwAQM" style="text-align:center;">220</td>
<td id="mwAQQ" style="text-align:center;">6,184</td>
<td id="mwAQU">Makati</td></tr>
<tr id="mwAQY">
<td id="mwAQc">25</td>
<td id="mwAQg"><a href="https://en.wikipedia.org/wiki/Monde_Nissin" id="mwAQk" rel="mw:WikiLink" title="Monde Nissin">Monde Nissin</a></td>
<td id="mwAQo">Food and beverage</td>
<td id="mwAQs" style="text-align:center;">1,442</td>
<td id="mwAQw" style="text-align:center;">(12)</td>
<td id="mwAQ0" style="text-align:center;">1,518</td>
<td id="mwAQ4"><a href="https://en.wikipedia.org/wiki/Santa_Rosa,_Laguna" id="mwAQ8" rel="mw:WikiLink" title="Santa Rosa, Laguna">Santa Rosa, Laguna</a></td></tr>
</tbody></table>

In [ ]:
table = soup.find('table', class_ = 'wikitable sortable', id = 'mwGg')

In [ ]:
table.find_all('th')

[<th id="mwHQ">Rank</th>,
 <th id="mwHg">Name</th>,
 <th id="mwHw">Industry</th>,
 <th id="mwIA">Revenue<br id="mwIQ"/><small id="mwIg">(USD millions)</small></th>,
 <th id="mwIw">Profits<br id="mwJA"/><small id="mwJQ">(USD millions)</small></th>,
 <th id="mwJg">Employees</th>,
 <th id="mwJw">Headquarters</th>]

In [ ]:
world_table_titles = [title.text.strip() for title in table.find_all('th')]
print(world_table_titles)

['Rank', 'Name', 'Industry', 'Revenue(USD millions)', 'Profits(USD millions)', 'Employees', 'Headquarters']

In [ ]:
import pandas

In [ ]:
df = pandas.DataFrame(columns = world_table_titles)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue(USD millions), Profits(USD millions), Employees, Headquarters]
Index: []

In [ ]:
column_data = table.find_all('tr')

In [ ]:
for row in column_data[1: ]:
  row_data = row.find_all('td')
  individual_row_data = [data.text.strip() for data in row_data]
  length = len(df)
  df.loc[length] = individual_row_data

  print(individual_row_data)

['1', 'San Miguel Corporation', 'Conglomerate', '26,024', '4', '53,184', 'Mandaluyong']
['2', 'SM Investments', 'Conglomerate', '10,277', '1,385', '72,770', 'Pasay']
['3', 'Manila Electric', 'Utilities', '7,980', '684', '14,494', 'Pasig']
['4', 'JG Summit Holdings', 'Conglomerate', '5,932', '361', '25,979', 'Pasig']
['5', 'Banco de Oro', 'Banking', '5,832', '1,321', '41,647', 'Mandaluyong']
['6', 'Aboitiz Equity Ventures', 'Conglomerate', '5,588', '424', '13,802', 'Taguig']
['7', 'Ayala Corporation', 'Conglomerate', '5,215', '685', '33,889', 'Makati']
['8', 'GT Capital', 'Conglomerate', '5,105', '517', '39,000', 'Makati']
['9', 'Jollibee Foods Corporation', 'Restaurants', '4,391', '158', '26,263', 'Pasig']
['10', 'Cosco Capital', 'Conglomerate', '3,858', '133', '12,982', 'Manila']
['11', 'PLDT', 'Telecommunications', '3,795', '479', '10,004', 'Makati']
['12', 'Alliance Global', 'Conglomerate', '3,683', '352', '56,915', 'Manila']
['13', 'Robinsons Retail', 'Retail', '3,456', '74', '23,172', 'Pasig']
['14', 'Metropolitan Bank & Trust', 'Banking', '3,292', '760', '18,810', 'Makati']
['15', 'Globe Telecom', 'Telecommunications', '3,241', '441', '7,542', 'Taguig']
['16', 'Bank of the Philippine Islands', 'Banking', '3,239', '930', '19,522', 'Makati']
['17', 'PAL Holdings', 'Airline', '3,222', '302', '5,109', 'Pasay']
['18', 'Lopez Holdings Corporation', 'Conglomerate', '2,967', '51', '11', 'Mandaluyong']
['19', 'International Container Terminal Services', 'Port management', '2,480', '512', '10,297', 'Manila']
['20', 'DMCI Holdings', 'Real estate', '2,210', '445', '17,620', 'Makati']
['21', 'LT Group', 'Conglomerate', '2,074', '457', '14,296', 'Taguig']
['22', 'Unionbank', 'Banking', '1,751', '163', '8,519', 'Pasig']
['23', 'Filinvest', 'Real estate', '1,670', '161', '12,979', 'Taguig']
['24', 'Rizal Commercial Banking', 'Banking', '1,487', '220', '6,184', 'Makati']
['25', 'Monde Nissin', 'Food and beverage', '1,442', '(12)', '1,518', 'Santa Rosa, Laguna']

In [ ]:
df

,Rank,Name,Industry,Revenue(USD millions),Profits(USD millions),Employees,Headquarters
0,1,San Miguel Corporation,Conglomerate,"26,024",4,"53,184",Mandaluyong
1,2,SM Investments,Conglomerate,"10,277","1,385","72,770",Pasay
2,3,Manila Electric,Utilities,"7,980",684,"14,494",Pasig
3,4,JG Summit Holdings,Conglomerate,"5,932",361,"25,979",Pasig
4,5,Banco de Oro,Banking,"5,832","1,321","41,647",Mandaluyong
5,6,Aboitiz Equity Ventures,Conglomerate,"5,588",424,"13,802",Taguig
6,7,Ayala Corporation,Conglomerate,"5,215",685,"33,889",Makati
7,8,GT Capital,Conglomerate,"5,105",517,"39,000",Makati
8,9,Jollibee Foods Corporation,Restaurants,"4,391",158,"26,263",Pasig
9,10,Cosco Capital,Conglomerate,"3,858",133,"12,982",Manila
10,11,PLDT,Telecommunications,"3,795",479,"10,004",Makati
11,12,Alliance Global,Conglomerate,"3,683",352,"56,915",Manila
12,13,Robinsons Retail,Retail,"3,456",74,"23,172",Pasig
13,14,Metropolitan Bank & Trust,Banking,"3,292",760,"18,810",Makati
14,15,Globe Telecom,Telecommunications,"3,241",441,"7,542",Taguig
15,16,Bank of the Philippine Islands,Banking,"3,239",930,"19,522",Makati
16,17,PAL Holdings,Airline,"3,222",302,"5,109",Pasay
17,18,Lopez Holdings Corporation,Conglomerate,"2,967",51,11,Mandaluyong
18,19,International Container Terminal Services,Port management,"2,480",512,"10,297",Manila
19,20,DMCI Holdings,Real estate,"2,210",445,"17,620",Makati
20,21,LT Group,Conglomerate,"2,074",457,"14,296",Taguig
21,22,Unionbank,Banking,"1,751",163,"8,519",Pasig
22,23,Filinvest,Real estate,"1,670",161,"12,979",Taguig
23,24,Rizal Commercial Banking,Banking,"1,487",220,"6,184",Makati
24,25,Monde Nissin,Food and beverage,"1,442",(12),"1,518","Santa Rosa, Laguna"